"""Initial revision

Revision ID: dcef69f171e0
Revises: 
Create Date: 2025-06-29 13:46:14.202158

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

from app.core.constants import SystemRoles

# revision identifiers, used by Alembic.
revision: str = 'dcef69f171e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор пользователя.'),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False,
                              comment='Дата и время создания записи пользователя.'),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False,
                              comment='Дата и время последнего обновления записи пользователя.'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
    )

    # Вставляем роли
    op.bulk_insert(
        sa.table(
            'roles',
            sa.Column('id', postgresql.UUID(as_uuid=True)),
            sa.column('name', sa.String),
            sa.column('created_at', sa.TIMESTAMP),
            sa.column('updated_at', sa.TIMESTAMP),
        ),
        [
            {'id': str(SystemRoles.USER), 'name': 'User'},
            {'id': str(SystemRoles.MODERATOR), 'name': 'Moderator'},
            {'id': str(SystemRoles.ADMIN), 'name': 'Admin'}
        ]
    )

    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=True)
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор пользователя.'),
                    sa.Column('role_id', sa.UUID(),
                              server_default=sa.text("'1259872b-f902-4d6c-b724-af4236bb32a6'::uuid"), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('phone_number', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False,
                              comment='Дата и время создания записи пользователя.'),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False,
                              comment='Дата и время последнего обновления записи пользователя.'),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('phone_number')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
